spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create


jwt:
  secret: SpringSecurity Java Web Token Secret Key
  grand-type: Bearer
  token-validate-in-seconds: 3600
