spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: validate

kakao:
  api:
    key: dd0c848e81e9871630e66d93e2e51d64
